import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import AntdProvider from "@/providers/AntdProvider";
import { SessionProvider } from "next-auth/react";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>

          <AntdProvider>
            <AuthProvider>
              {children}
            </AuthProvider>
          </AntdProvider>
        </SessionProvider>

      </body>
    </html>
  );
}
